---
commonLabels:
  observeinc.com/component: 'events'

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: kube-state-events-env
    literals:
      - OBSERVE_COLLECTOR_HOST=collect.observeinc.com
      - OBSERVE_COLLECTOR_PORT=443
      - V=2

images:
  - name: observeinc/kube-state-events
    newTag: 'v0.6.2'
  - name: observeinc/kube-cluster-info
    newTag: 'v0.6.2'
