---
bases:
  - ../base
namePrefix: observe-
resources:
  - deployment.yaml
commonLabels:
  observeinc.com/component: 'traces'
images:
  - name: otel/opentelemetry-collector-contrib
    newTag: '0.88.0'
