name: Update via Updatecli

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install and run updatecli
      - name: Setup updatecli
        uses: updatecli/updatecli-action@v2

      - name: Run updatecli
        run: |
          for config in updatecli/*.yaml; do
            updatecli apply --config $config
          done
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use Peter Evans Pull Request Action to create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): Update dependencies"
          title: 'chore(deps): Update dependencies'
          body: |
            Updates dependencies using `updatecli`.
          branch: automated-update-${{ github.run_number }}
          labels: automated-pr, update
          draft: false
